
package Interfaz;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MantenimientoVendedores extends javax.swing.JDialog {

      DefaultTableModel modelo;
      private int filaseleccionadas;
      
    public MantenimientoVendedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//pantalla central
        setTitle("Mantenimiento de Vendedores");
        setIconImage(new ImageIcon(getClass().getResource("/imagen/bellota.jpg")).getImage());
        
        modelo=new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("EstadoCicil");
        this.TablaVendedores.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVendedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EstadoCivil = new javax.swing.JTextField();
        Comuna = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Comuna");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaVendedores);

        jLabel1.setText("Datos del Vendedor:");

        jLabel2.setText("Rut:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("EstadoCivil");

        Comuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunaActionPerformed(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jLabel8.setText("Comuna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Agregar))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Modificar)
                                .addGap(29, 29, 29)
                                .addComponent(Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(Rut)
                                    .addComponent(Apellido))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 239, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Eliminar)
                    .addComponent(Salir)
                    .addComponent(Modificar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunaActionPerformed

    
    public static boolean validarRut(String rut) {  
  
  boolean validacion = false;  
  try 
  {  
   rut =  rut.toUpperCase();  
   rut = rut.replace(".", "");  
   rut = rut.replace("-", "");  
   int rutAux = Integer.parseInt(rut.substring(0, rut.length() - 1));  
  
   char dv = rut.charAt(rut.length() - 1);  
  
   int m = 0, s = 1;  
   for (; rutAux != 0; rutAux /= 10) 
   {  
   s = (s + rutAux % 10 * (9 - m++ % 6)) % 11;  
   }  
   if (dv == (char) (s != 0 ? s + 47 : 75)) 
   {  
   validacion = true;  
   }  
  
   } catch (java.lang.NumberFormatException e) {  
   } catch (Exception e) {  
   }  
   return validacion;  
}
    
    
    
    
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
    
     Vendedor obj = new Vendedor();
     int ct=0;
     obj.setRutVendedor(Rut.getText());
     obj.setNombres(Nombre.getText()); 
     obj.setApellidos(Apellido.getText());
     obj.setTelefono(Telefono.getText());
     obj.setEstadoCivil(EstadoCivil.getText());
     obj.setComuna(Comuna.getText());
     
     if (Rut.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Rut Vacio");
            ct++;
        }
    
      String rut1=Rut.getText();
     if (!validarRut(rut1))
     {
         JOptionPane.showMessageDialog(this, "Rut ERRONEO - INSERTE UN RUT VALIDO");
         ct++;
     }
     
     
     if (Nombre.getText().equals("")) { // pregunta si esta vacio
            JOptionPane.showMessageDialog(this, "Campo NOMBRE Vacio");
            ct++;
        }
     
     if (Apellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo APELLIDO Vacio");
            ct++;
        }
     
     if (Telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo TELEFONO Vacio");
            ct++;
        }
     
     if (EstadoCivil.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Estado Civil Vacio");
            ct++;
        }
     
     if (Comuna.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Comuna Vacio");
            ct++;
        }
     
     if(! Nombre.getText().matches("[a-z]*")) 
       {
           
           JOptionPane.showMessageDialog(this, "Error al guardar NOMBRE - Caracter o numero invalido ");
           ct++;
       }
     
     if(! Comuna.getText().matches("[a-z]*")) 
       {
           
           JOptionPane.showMessageDialog(this, "Error al guardar Comuna - Caracter o numero invalido ");
           ct++;
       }
     
     if(! Apellido.getText().matches("[a-z]*")) 
       {
           
           JOptionPane.showMessageDialog(this, "Error al guardar Apellido - Caracter o numero invalido ");
           ct++;
       }
     
     if(! EstadoCivil.getText().matches("[a-z]*")) 
       {
           
           JOptionPane.showMessageDialog(this, "Error al guardar EstadoCivil - Caracter o numero invalido ");
           ct++;
       }
     
     if(Telefono.getText().matches("[a-z]*")) 
       {
           
           JOptionPane.showMessageDialog(this, "Error al guardar nombre - caracter o numero invalido");
           ct++;
       }
     
     if(obj.guardarVendedor() && ct==0 )
    {
        JOptionPane.showMessageDialog(this, "Datos Guardados");
        
    }                                       
    else
    {
        JOptionPane.showMessageDialog(this, "Error al guardar datos");
    }


      
    }//GEN-LAST:event_AgregarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    public void limpiarVendedor(){
    Rut.setText("");
    Nombre.setText("");
    Apellido.setText("");
    Telefono.setText("");
    EstadoCivil.setText("");
    Comuna.setText("");
     }
    
    
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         
    Vendedor obj = new Vendedor();
    obj.setRutVendedor(Rut.getText());
    int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea ELIMINAR?",
            "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if(eliminar == 0)
    {
        if(obj.eliminarVendedor())
        {
            JOptionPane.showMessageDialog(this, "Datos Eliminados");
            //limpiar();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error al Eliminar");
        }
    }
                                 
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
       
     Vendedor obj = new Vendedor();
    
     obj.setRutVendedor(Rut.getText());
     obj.setNombres(Nombre.getText()); 
     obj.setApellidos(Apellido.getText());
     obj.setTelefono(Telefono.getText());
     obj.setEstadoCivil(EstadoCivil.getText());
     obj.setComuna(Comuna.getText());
    
     if(obj.modificarVendedor())
    {
        JOptionPane.showMessageDialog(this, "Datos Modificados");
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Error al Modificar");
    }
                                      
        
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MantenimientoVendedores dialog = new MantenimientoVendedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Comuna;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField EstadoCivil;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Rut;
    private javax.swing.JButton Salir;
    private javax.swing.JTable TablaVendedores;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
